<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<style>
    .alert_success_card_save{
        background-color: #d4edfc;
    }
    .Rectangle {
        display: flex;
        padding: 0 43px 0 0;
        border-radius: 2px;
        background-color: #d4edfc;
    }
    .Rectangle-Copy {
        display: inline-block;
        width: 3.1px;
        height: 41.5px;
        margin: 0 5.9px 0 0;
        border-radius: 2px;
        background-color: #1464a5;
    }
    .img_notification_card{
        margin-top: 8px;
    }

    .checkout-success-openpay-cards {
        margin: 20px 0;
    }
</style>
<div class="checkout-success-openpay-cards">
    <?php if ($block->getOrderId()): ?>

        <?php if (isset($_SESSION['card_new']) && ($_SESSION['card_new'] == '1' || $_SESSION['card_new'] == '2')): ?>
            <div class="Rectangle">
                <div class="Rectangle-Copy"></div>
                <img src="https://img.openpay.mx/plugins/communication-and-multimedia-alarm.png" class="img_notification_card" style="height: 20px">
                <span class="img_notification_card">
                    <strong> Tu tarjeta fue registrada correctamente </strong>
                </span>
            </div>
            <?php unset($_SESSION['card_new']); ?>
        <?php endif; ?>

        <?php if ($block->getCanViewOrder()) : ?>
            <p><?php echo __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php endif; ?>
        
    <?php endif; ?>
</div>
